### ISSUE TITLE
Plugin does not work with ornament kitted godbooks

### ISSUE THREAD

**Issue by AnuVen** [InfernoStats/godbook#1]
Doesn't work if someone has a shattered relics ornament kit on godbook

**Comment by InfernoStats** [comment]
Resolved in 62e4b93ad66705c4d900cef1dab85b64aa608914

**Comment by InfernoStats** [comment]
This update will be in version 1.0.2. You can follow the plugin-hub PR here: https://github.com/runelite/plugin-hub/pull/3176
